const products=[['Chicken Suya',8200,'chicken-suya.webp','Spicy chicken, red onion and Lagos suya attitude.'],['Pepperoni',8200,'pepperoni.webp','Pepperoni, mozzarella and tomato sauce.'],['Dodo BBQ',8500,'bbq.webp','Chicken, peppers and glossy barbecue sauce.'],['Margherita',7200,'margherita.webp','Tomato, mozzarella and basil.'],['Dodo Supreme',9000,'supreme.webp','Loaded, colourful and built for a serious craving.'],['Veggie Overload',8200,'veggie.webp','Mushrooms, peppers, olives, onions and tomato.']];
const fmt=n=>'₦'+n.toLocaleString('en-NG'),clamp=(v,a,b)=>Math.min(b,Math.max(a,v)),mix=(a,b,t)=>a+(b-a)*t;
const smoothstep=(a,b,v)=>{const t=clamp((v-a)/(b-a),0,1);return t*t*(3-2*t)};
const easeOutCubic=t=>1-Math.pow(1-t,3);
let cart=[];try{cart=JSON.parse(localStorage.getItem('dodoYabaCart')||'[]')}catch(e){cart=[]}
function saveCart(){localStorage.setItem('dodoYabaCart',JSON.stringify(cart))}

const story=document.querySelector('.story'),rig=document.querySelector('#rig'),intro=document.querySelector('#intro'),ings=[...document.querySelectorAll('.ingredients span')],labels=['THE INGREDIENTS','THE OVEN','THE BUILD','YOUR SLICE'];
const canvas=document.querySelector('#assemblyCanvas'),ctx=canvas.getContext('2d'),finalPizza=document.querySelector('#finalPizza');
const imageFiles={dough:'assembly-dough.webp',sauce:'assembly-sauce.webp',cheese:'assembly-cheese.webp',pep:'assembly-pepperoni.webp',mush:'assembly-mushrooms.webp',onion:'assembly-onions.webp',greens:'assembly-greens.webp'};
const imgs={}; let loaded=0;
Object.entries(imageFiles).forEach(([k,f])=>{const im=new Image();im.src='assets/'+f;im.onload=()=>{loaded++;};imgs[k]=im});
let targetRaw=0,currentRaw=0;
function targetFromScroll(){const r=story.getBoundingClientRect(),max=Math.max(1,story.offsetHeight-innerHeight);targetRaw=clamp(-r.top/max,0,1);document.querySelector('#progress').style.width=(scrollY/(document.documentElement.scrollHeight-innerHeight)*100)+'%'}
addEventListener('scroll',targetFromScroll,{passive:true});addEventListener('resize',targetFromScroll);targetFromScroll();

function drawImageFit(img,cx,cy,w,h,alpha=1,rot=0){if(!img||!img.complete)return;ctx.save();ctx.globalAlpha=alpha;ctx.translate(cx,cy);ctx.rotate(rot);ctx.drawImage(img,-w/2,-h/2,w,h);ctx.restore()}
function toppingMask(){ctx.beginPath();ctx.ellipse(450,450,260,225,0,0,Math.PI*2);ctx.clip()}
function drawIngredient(img,start,end,p,scaleStart,scaleEnd,rotStart=0,rotEnd=0,alpha=1){const t=easeOutCubic(clamp(p,0,1)),x=mix(start[0],end[0],t),y=mix(start[1],end[1],t),s=mix(scaleStart,scaleEnd,t),r=mix(rotStart,rotEnd,t);drawImageFit(img,x,y,img.width*s,img.height*s,alpha,r)}
function renderAssembly(p){ctx.clearRect(0,0,900,900);if(loaded<7)return;
  const doughT=smoothstep(0,.17,p);drawImageFit(imgs.dough,450,mix(515,450,doughT),720*doughT,720*doughT,doughT,mix(-.12,0,doughT));
  ctx.save();toppingMask();
  const sauceT=smoothstep(.09,.28,p);drawImageFit(imgs.sauce,450,450,540*sauceT,500*sauceT,sauceT,mix(.12,0,sauceT));
  const cheeseT=smoothstep(.21,.43,p);drawIngredient(imgs.cheese,[310,160],[450,450],cheeseT,.16,.36,-.22,0,cheeseT);
  const pepT=smoothstep(.34,.58,p);drawIngredient(imgs.pep,[720,190],[455,445],pepT,.18,.34,.3,0,pepT);
  const mushT=smoothstep(.41,.64,p);drawIngredient(imgs.mush,[170,255],[430,450],mushT,.18,.30,-.26,0,mushT);
  const onionT=smoothstep(.47,.69,p);drawIngredient(imgs.onion,[185,700],[458,458],onionT,.15,.27,-.2,0,onionT);
  const greenT=smoothstep(.53,.74,p);drawIngredient(imgs.greens,[735,690],[465,452],greenT,.16,.28,.22,0,greenT);
  ctx.restore();
  const heat=smoothstep(.68,.86,p);if(heat>0){ctx.save();ctx.globalCompositeOperation='source-atop';ctx.fillStyle=`rgba(244,81,18,${heat*.10})`;ctx.fillRect(150,150,600,600);ctx.restore();}
}
function updateStory(raw){const s=raw*4,c=Math.min(3,Math.floor(s+.02));document.querySelector('#idx').textContent=String(c+1).padStart(2,'0');document.querySelector('#idxText').textContent=labels[c];
  let x=18,y=7,rx=58,ry=-16,rz=-8,sc=.72,op=1;if(s<1){const t=s;x=mix(18,7,t);y=mix(7,-3,t);rx=mix(58,48,t);ry=mix(-16,10,t);rz=mix(-8,9,t);sc=mix(.72,.90,t);intro.style.opacity=1-clamp(t*1.12,0,1);intro.style.transform=`translateY(${-t*42}px)`}else if(s<2){const t=s-1;x=mix(7,17,t);y=mix(-3,5,t);rx=mix(48,69,t);ry=mix(10,-18,t);rz=mix(9,-16,t);sc=mix(.90,1,t);intro.style.opacity=0}else if(s<3){const t=s-2;x=mix(17,-10,t);y=mix(5,-2,t);rx=mix(69,43,t);ry=mix(-18,20,t);rz=mix(-16,11,t);sc=mix(1,.86,t)}else{const t=s-3;x=mix(-10,3,t);y=mix(-2,4,t);rx=mix(43,61,t);ry=mix(20,0,t);rz=mix(11,0,t);sc=mix(.86,.58,t);op=mix(1,.08,clamp((t-.58)*2.15,0,1))}
  rig.style.transform=`translate3d(calc(-50% + ${x}vw),calc(-50% + ${y}vh),0) rotateX(${rx}deg) rotateY(${ry}deg) rotateZ(${rz}deg) scale(${sc})`;rig.style.opacity=op;
  const assemblyP=clamp(s/1.02,0,1),finalP=smoothstep(.78,1.01,assemblyP);story.classList.toggle('is-assembling',assemblyP<.98);renderAssembly(assemblyP);
  canvas.style.opacity=String(1-smoothstep(.82,1,assemblyP));canvas.style.filter=`drop-shadow(0 28px 38px rgba(74,24,3,.24)) blur(${mix(0,2.5,finalP)}px)`;
  finalPizza.style.opacity=String(finalP);finalPizza.style.transform=`translateZ(${mix(20,35,finalP)}px) scale(${mix(.92,1,finalP)}) rotate(${mix(-4,0,finalP)}deg)`;finalPizza.style.filter=`drop-shadow(0 35px 45px rgba(74,24,3,.28)) blur(${mix(3,0,finalP)}px)`;
  ings.forEach((el,i)=>{const rev=clamp((s-1.72)*1.6-i*.07,0,1),dr=(raw-.5)*(i%2?70:-65);el.style.opacity=assemblyP<.98?0:rev;el.style.transform=`translate(${dr}px,${(1-rev)*34}px) rotate(${dr*.04}deg)`});
}
function animationLoop(){currentRaw += (targetRaw-currentRaw)*.075;if(Math.abs(targetRaw-currentRaw)<.0001)currentRaw=targetRaw;updateStory(currentRaw);requestAnimationFrame(animationLoop)}requestAnimationFrame(animationLoop);
document.querySelector('#track').innerHTML=products.map((p,i)=>`<article class="product"><img src="assets/${p[2]}" alt="${p[0]}"><div class="meta"><h3>${p[0]}</h3><p>${p[3]}</p><div class="buy"><b>${fmt(p[1])}</b><button data-add="${i}">+</button></div></div></article>`).join('');function addItem(x){cart.push({...x,id:Date.now()+Math.random()});saveCart();render()}document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{const p=products[+b.dataset.add];addItem({name:p[0],price:p[1]})});
const builderAssets={dough:'assets/assembly-dough.webp',sauce:'assets/assembly-sauce.webp',cheese:'assets/assembly-cheese.webp',pepperoni:'assets/assembly-pepperoni.webp',mushrooms:'assets/assembly-mushrooms.webp',onions:'assets/assembly-onions.webp',greens:'assets/assembly-greens.webp'};
const builderImages={};let builderReady=0;Object.entries(builderAssets).forEach(([k,src])=>{const im=new Image();im.onload=()=>{builderReady++;drawBuilder(true)};im.src=src;builderImages[k]=im});
const sizes=[['Medium',8200,1],['Large',9800,1.09],['Extra Large',11200,1.16]],crusts=[['Original',0],['Thin',0]];
const toppingDefs={Pepperoni:{key:'pepperoni',price:900},Mushrooms:{key:'mushrooms',price:650},'Red onion':{key:'onions',price:450},'Bell pepper & basil':{key:'greens',price:500}};
const combos={Pepperoni:['Pepperoni'],Veggie:['Mushrooms','Red onion','Bell pepper & basil'],Supreme:['Pepperoni','Mushrooms','Red onion','Bell pepper & basil']};
let buildState={size:'Medium',crust:'Original',toppings:[]};
const builderCanvas=document.querySelector('#builderCanvas'),builderCtx=builderCanvas.getContext('2d');
function containImage(img,cx,cy,maxW,maxH,alpha=1,rot=0,scale=1){if(!img||!img.complete)return;const ratio=Math.min(maxW/img.naturalWidth,maxH/img.naturalHeight)*scale,w=img.naturalWidth*ratio,h=img.naturalHeight*ratio;builderCtx.save();builderCtx.globalAlpha=alpha;builderCtx.translate(cx,cy);builderCtx.rotate(rot);builderCtx.drawImage(img,-w/2,-h/2,w,h);builderCtx.restore()}
function clipPizza(){builderCtx.beginPath();builderCtx.ellipse(380,380,258,220,0,0,Math.PI*2);builderCtx.clip()}
function drawBuilder(){if(builderReady<7)return;builderCtx.clearRect(0,0,760,760);const sizeScale=sizes.find(x=>x[0]===buildState.size)[2];builderCtx.save();builderCtx.translate(380,380);builderCtx.scale(sizeScale,sizeScale);builderCtx.translate(-380,-380);containImage(builderImages.dough,380,380,590,590,1,0,1);builderCtx.save();clipPizza();containImage(builderImages.sauce,380,380,438,438,.96,0,1);containImage(builderImages.cheese,380,380,468,468,.90,0,1.02);const selected=buildState.toppings;selected.forEach(name=>{const def=toppingDefs[name],img=builderImages[def.key];const configs={Pepperoni:[[300,305,.43,-.13],[420,290,.42,.08],[480,385,.39,-.05],[355,430,.41,.1],[445,475,.36,-.1]],Mushrooms:[[320,320,.28,-.2],[465,330,.26,.16],[305,445,.25,.08],[455,455,.29,-.12]],'Red onion':[[345,290,.27,-.2],[480,410,.24,.18],[330,455,.25,.1]],'Bell pepper & basil':[[420,340,.29,.12],[310,380,.24,-.15],[425,460,.24,-.05]]};(configs[name]||[]).forEach(([x,y,s,r])=>containImage(img,x,y,260,260,1,r,s));});builderCtx.restore();builderCtx.restore();const base=sizes.find(x=>x[0]===buildState.size)[1],extra=selected.reduce((n,t)=>n+toppingDefs[t].price,0);document.querySelector('#buildPrice').textContent=fmt(base+extra);document.querySelector('#buildName').textContent=(selected.length?selected.join(' · '):'CHEESE BASE').toUpperCase();}
function builderButtons(){document.querySelector('#sizeBtns').innerHTML=sizes.map(x=>`<button class="${x[0]===buildState.size?'active':''}" data-size="${x[0]}">${x[0]}</button>`).join('');document.querySelector('#crustBtns').innerHTML=crusts.map(x=>`<button class="${x[0]===buildState.crust?'active':''}" data-crust="${x[0]}">${x[0]}</button>`).join('');document.querySelector('#comboBtns').innerHTML=Object.keys(combos).map(n=>`<button data-combo="${n}">${n}</button>`).join('');document.querySelector('#toppingBtns').innerHTML=Object.keys(toppingDefs).map(n=>`<button class="${buildState.toppings.includes(n)?'active':''}" data-top="${n}">${n}</button>`).join('');document.querySelectorAll('[data-size]').forEach(b=>b.onclick=()=>{buildState.size=b.dataset.size;builderButtons();drawBuilder()});document.querySelectorAll('[data-crust]').forEach(b=>b.onclick=()=>{buildState.crust=b.dataset.crust;builderButtons();drawBuilder()});document.querySelectorAll('[data-combo]').forEach(b=>b.onclick=()=>{buildState.toppings=[...combos[b.dataset.combo]];builderButtons();document.querySelectorAll('[data-combo]').forEach(x=>x.classList.toggle('active',x.dataset.combo===b.dataset.combo));drawBuilder()});document.querySelectorAll('[data-top]').forEach(b=>b.onclick=()=>{const n=b.dataset.top;buildState.toppings=buildState.toppings.includes(n)?buildState.toppings.filter(x=>x!==n):[...buildState.toppings,n];builderButtons();drawBuilder()});}
builderButtons();document.querySelector('#resetBuild').onclick=()=>{buildState.toppings=[];builderButtons();drawBuilder()};
const bv=document.querySelector('.buildvisual'),br=document.querySelector('#buildRig');bv.onpointermove=e=>{const r=bv.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;br.style.transform=`rotateX(${6-y*8}deg) rotateY(${x*10}deg) rotateZ(${x*2}deg)`};bv.onpointerleave=()=>br.style.transform='rotateX(0deg) rotateY(0deg)';document.querySelector('#addBuild').onclick=()=>{const base=sizes.find(x=>x[0]===buildState.size)[1],extra=buildState.toppings.reduce((n,t)=>n+toppingDefs[t].price,0);addItem({name:`${buildState.size} ${buildState.crust} ${buildState.toppings.length?buildState.toppings.join(' + '):'Cheese Pizza'}`,price:base+extra})};
function render(){document.querySelector('#cartCount').textContent=cart.length;document.querySelector('#total').textContent=fmt(cart.reduce((n,i)=>n+i.price,0));document.querySelector('#items').innerHTML=cart.length?cart.map(i=>`<div class="cartrow"><div><b>${i.name}</b><br><small>${fmt(i.price)}</small></div><button data-r="${i.id}">Remove</button></div>`).join(''):'<p>Your cart is empty.</p>';document.querySelectorAll('[data-r]').forEach(b=>b.onclick=()=>{cart=cart.filter(i=>String(i.id)!==b.dataset.r);saveCart();render()})}render();const dlg=document.querySelector('#cart');document.querySelector('#cartOpen').onclick=()=>dlg.showModal();document.querySelector('#close').onclick=()=>dlg.close();addEventListener('scroll',()=>{const e=document.querySelector('.marquee'),r=e.getBoundingClientRect();if(r.top<innerHeight&&r.bottom>0){const p=clamp((innerHeight-r.top)/(innerHeight+r.height),0,1);document.querySelector('#marquee').style.transform=`translateX(${mix(-28,4,p)}vw)`}},{passive:true});